CREATE TABLE `video_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`videoUrl` text NOT NULL,
	`platform` varchar(64),
	`videoId` varchar(255),
	`title` text,
	`description` text,
	`author` varchar(255),
	`authorId` varchar(255),
	`coverUrl` text,
	`playUrl` text,
	`duration` int,
	`hashtags` json,
	`viewCount` bigint,
	`likeCount` bigint,
	`commentCount` bigint,
	`shareCount` bigint,
	`status` enum('pending','downloading','extracting','analyzing','completed','failed') NOT NULL DEFAULT 'pending',
	`progress` int DEFAULT 0,
	`errorMessage` text,
	`subtitles` text,
	`ocrText` text,
	`frameAnalysis` json,
	`contentSummary` text,
	`keyPoints` json,
	`videoFileKey` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `video_analyses_id` PRIMARY KEY(`id`)
);
